# Generated by Django 4.0.3 on 2023-01-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='email',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='department',
            name='phone',
            field=models.CharField(max_length=60),
        ),
    ]
