# Generated by Django 4.0.3 on 2023-01-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties_app', '0002_alter_department_email_alter_department_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='bachelors_count',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='employee_count',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='master_count',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
