# Generated by Django 4.0.3 on 2023-01-18 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculties_app', '0004_alter_department_bachelors_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='faculties_app.faculty'),
        ),
    ]
