# Generated by Django 4.0.3 on 2023-01-18 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculties_app', '0005_alter_department_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='bachelors_count',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='department',
            name='employee_count',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculties_app.faculty'),
        ),
        migrations.AlterField(
            model_name='department',
            name='master_count',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='department',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
